version: '3'
services:
  nodejs:
    container_name: node_server
    image: node:latest
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      - TZ=America/Sao_Paulo
    command: bash -c "npm install && npm start"